name: castle
options:
  bundleIdPrefix: com.castle
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"
  
settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: minimal
    ENABLE_USER_SCRIPT_SANDBOXING: false
    
targets:
  castle:
    type: application
    platform: iOS
    sources:
      - path: castle/Sources
        type: group
      - path: castle/GoogleService-Info.plist
      - path: castle/Resources/rooms_data.json
        buildPhase: resources
    info:
      path: castle/Info.plist
      properties:
        CFBundleDisplayName: Castle
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
    entitlements:
      path: castle/castle.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mostlycached.castle
        INFOPLIST_FILE: castle/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
    dependencies:
      - package: firebase-ios-sdk
        products:
          - FirebaseAuth
          - FirebaseFirestore
          - FirebaseFunctions
          
packages:
  firebase-ios-sdk:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "11.0.0"

schemes:
  castle:
    build:
      targets:
        castle: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
